apiVersion: v1
kind: Node
metadata:
  annotations:
    alpha.kubernetes.io/provided-node-ip: 192.168.1.114,2605:a601:a6cd:4100::142
    flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"ee:5a:a3:7f:96:18"}'
    flannel.alpha.coreos.com/backend-type: vxlan
    flannel.alpha.coreos.com/kube-subnet-manager: "true"
    flannel.alpha.coreos.com/public-ip: 192.168.1.114
    k3s.io/hostname: jetson
    k3s.io/internal-ip: 192.168.1.114,2605:a601:a6cd:4100::142
    k3s.io/node-args: '["server","--default-runtime","nvidia","--disable","traefik"]'
    k3s.io/node-config-hash: PYGYPSW7A54V6IX7YYVPKYRBVQSAMYEZOH4JF4VPZFKHGDKQ6JQA====
    k3s.io/node-env: '{}'
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2025-03-22T14:25:55Z"
  finalizers:
  - wrangler.cattle.io/node
  labels:
    beta.kubernetes.io/arch: arm64
    beta.kubernetes.io/instance-type: k3s
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: arm64
    kubernetes.io/hostname: jetson
    kubernetes.io/os: linux
    node-role.kubernetes.io/control-plane: "true"
    node-role.kubernetes.io/master: "true"
    node.kubernetes.io/instance-type: k3s
  name: jetson
  resourceVersion: "2841"
  uid: 0f5265b5-0dcd-413f-b8db-be15b5b8d2a9
spec:
  podCIDR: 10.42.0.0/24
  podCIDRs:
  - 10.42.0.0/24
  providerID: k3s://jetson
status:
  addresses:
  - address: 192.168.1.114
    type: InternalIP
  - address: 2605:a601:a6cd:4100::142
    type: InternalIP
  - address: jetson
    type: Hostname
  allocatable:
    cpu: "8"
    ephemeral-storage: "236898146938"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    hugepages-32Mi: "0"
    hugepages-64Ki: "0"
    memory: 16032388Ki
    pods: "110"
  capacity:
    cpu: "8"
    ephemeral-storage: 243521944Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    hugepages-32Mi: "0"
    hugepages-64Ki: "0"
    memory: 16032388Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2025-03-22T16:29:19Z"
    lastTransitionTime: "2025-03-22T14:25:55Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2025-03-22T16:29:19Z"
    lastTransitionTime: "2025-03-22T14:25:55Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2025-03-22T16:29:19Z"
    lastTransitionTime: "2025-03-22T14:25:55Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2025-03-22T16:29:19Z"
    lastTransitionTime: "2025-03-22T14:25:55Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - docker.io/nvidia/cuda@sha256:7df325b76ef5087ac512a6128e366b7043ad8db6388c19f81944a28cd4157368
    - docker.io/nvidia/cuda:12.2.2-runtime-ubuntu20.04
    sizeBytes: 1303909031
  - names:
    - docker.io/library/nginx@sha256:124b44bfc9ccd1f3cedf4b592d4d1e8bddb78b51ec2ed5056c52d3692baebc19
    - docker.io/library/nginx:latest
    sizeBytes: 68634448
  - names:
    - docker.io/rancher/local-path-provisioner@sha256:80496fdeb307541007621959aa13aed41d31db9cd2dc4167c19833e0bfa3878c
    - docker.io/rancher/local-path-provisioner:v0.0.31
    sizeBytes: 19803489
  - names:
    - docker.io/rancher/mirrored-coredns-coredns@sha256:82979ddf442c593027a57239ad90616deb874e90c365d1a96ad508c2104bdea5
    - docker.io/rancher/mirrored-coredns-coredns:1.12.0
    sizeBytes: 19148178
  - names:
    - docker.io/rancher/mirrored-metrics-server@sha256:dccf8474fb910fef261d31d9483d7e4c1df7b86cf4d638fb6a7d7c88bd51600a
    - docker.io/rancher/mirrored-metrics-server:v0.7.2
    sizeBytes: 17862421
  - names:
    - docker.io/rancher/mirrored-pause@sha256:74c4244427b7312c5b901fe0f67cbc53683d06f4f24c6faee65d4182bf0fa893
    - docker.io/rancher/mirrored-pause:3.6
    sizeBytes: 253243
  nodeInfo:
    architecture: arm64
    bootID: b6deb694-dce9-4cf2-acc3-84f7cf85dce7
    containerRuntimeVersion: containerd://2.0.2-k3s2
    kernelVersion: 5.15.136-tegra
    kubeProxyVersion: v1.31.6+k3s1
    kubeletVersion: v1.31.6+k3s1
    machineID: 5dbfb12414a3456d9014d88183e338b1
    operatingSystem: linux
    osImage: Ubuntu 22.04.4 LTS
    systemUUID: 5dbfb12414a3456d9014d88183e338b1
  runtimeHandlers:
  - features:
      recursiveReadOnlyMounts: true
      userNamespaces: true
    name: nvidia
  - features:
      recursiveReadOnlyMounts: true
      userNamespaces: true
    name: ""
  - features:
      recursiveReadOnlyMounts: false
      userNamespaces: false
    name: runhcs-wcow-process
  - features:
      recursiveReadOnlyMounts: true
      userNamespaces: true
    name: runc
