kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # add a mount from /path/to/my/files on the host to /files on the node
  extraMounts:
  - hostPath: /home/csantana/jetson-containers/data
    containerPath: /jetson-containers/data
  - hostPath: /dev/null
    containerPath: /var/run/nvidia-container-devices/all

