# pod-using-hostpath.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-using-hostpath
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - mountPath: "/data"
          name: hostpath-volume
  volumes:
    - name: hostpath-volume
      persistentVolumeClaim:
        claimName: ollama-pvc