apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ollama-ui
  name: ollama-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-ui
  template:
    metadata:
      labels:
        app: ollama-ui
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: ollama-ui
        image: ghcr.io/open-webui/open-webui:main
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama"
