apiVersion: v1
kind: Service
metadata:
  labels:
    app: ollama-ui
  name: ollama-ui
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ollama-ui
  type: LoadBalancer

